name: My Second Pipeline

run-name: ${{ github.actor }} is automating workflows with ${{ github.workflow }}

on: 
  push:
    branches: 
      - main

jobs:
  render-figlet-banner:
    runs-on: ubuntu-latest

# always start with checkout repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      # install figlet library, you can see lots from marketplace on the right side 
      - name: Install figlet
        run: sudo apt-get update && sudo apt-get install -y figlet lolcat

      - name: Print figlet banner from notes.txt
        run: |
          TEXT="$(cat notes.txt)"
          figlet -f slant "$TEXT"

  render-cowsay-banner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        # cowsay is a library 
      - name: Install cowsay # -y flag to automatically yes to interactive install
        run: sudo apt-get update && sudo apt-get install -y cowsay && sudo  apt-get install -y cowsay-dev

      - name: Print cowsay banner from notes.txt
        run: |
          TEXT="$(cat notes.txt)"
          cowsay "$TEXT"
          cowsay -f dolphin "Hello from the ocean!"
